### ISSUE TITLE
Signed PDF size?

### ISSUE THREAD

**Issue by michael79bxl** [perevoznyk/swelio-pdf#2]
Hi,

I noticed the signed file is ~1MB bigger than the original.
Is this normal, or is there a way to have a ligther version?

Thanks,

Regards,

Michael

**Comment by perevoznyk** [comment]
PDFSigner implements long term signature for archiving purposes standard. It is normal to have 1MB size increasing. It is possible to make it smaller, but the implemented standard will be different, for example simple CMS or CADES-B. This depends from the purpose of the signature. How long do you plan to keep document, etc...

**Comment by michael79bxl** [comment]
Thanks. This is very helpful. It would be nice to have this as an output option. We might have different planed duration depending on the document type.

**Comment by perevoznyk** [comment]
The purpose of swelio-pdf project is to provide library for developers, not the final product. PDFSigner is just a simple example how to integrate library in the product.

**Comment by michael79bxl** [comment]
OK. I might fork the sample to a full tool then. Thanks for your help.
